### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by JadinAndrews** [usewaypoint/email-builder-js#101]
Hi Team, I just discovered email-builder today, I'm quite keen to get involved and assist with new features, but it will take me a bit of time to get up to speed with the current codebase. 

The first enhancement I would suggest is the ability to configure Tags that can be included in various text areas, IE, {customer_name}, {custom_tag1} etc, which can then be parsed by a sending system to replace those tags before sending the final email. The request here is simply to allow us to specify a list of common tags selectable from a drop down, that are automatically inserted at the current cursor location when a user creates a new template. This saves from having to manually type out the codes.

**Comment by jordanisip** [comment]
This is a good idea, however, our current plan is to keep EmailBuilder.js pretty stripped down as we have a pro version on [Waypoint](https://usewaypoint.com/) with similar functionality. It's something we might consider porting over in the future. In the meantime, you are more than welcome to fork and customize as needed.

**Comment by markyun** [comment]
add  liquidjs  to  `@usewaypoint/editor-sample`
