### ISSUE TITLE
Feature request to add hyperlink to text

### ISSUE THREAD

**Issue by arunudayan** [usewaypoint/email-builder-js#103]
There is no way to add hyperlink to a text

**Comment by jordanisip** [comment]
This is a good request and have others ask for it in the past as well. Our current text block is focused on simple plain text, however, we are considering adding a Markdown block that will make simple formatting and linking much more convenient.

**Comment by jordanisip** [comment]
@arunudayan @fomalhautb – good news, we've added a 'Markdown' switch on our text block:

<img width="1512" alt="CleanShot 2024-06-03 at 12 00 17@2x" src="https://github.com/usewaypoint/email-builder-js/assets/5899/cdf58167-8c9e-4fd6-8b94-cf5789e181dc">

This processes the text through [GitHub flavored Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) and makes adding links and basic formatting much more convenient. 

You can [see this in action on our playground](https://usewaypoint.github.io/email-builder-js/#code/JTdCJTIycm9vdCUyMiUzQSU3QiUyMnR5cGUlMjIlM0ElMjJFbWFpbExheW91dCUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJiYWNrZHJvcENvbG9yJTIyJTNBJTIyJTIzRjJGNUY3JTIyJTJDJTIyYm9yZGVyUmFkaXVzJTIyJTNBMjQlMkMlMjJjYW52YXNDb2xvciUyMiUzQSUyMiUyM0ZGRkZGRiUyMiUyQyUyMnRleHRDb2xvciUyMiUzQSUyMiUyMzI0MjQyNCUyMiUyQyUyMmZvbnRGYW1pbHklMjIlM0ElMjJNT0RFUk5fU0FOUyUyMiUyQyUyMmNoaWxkcmVuSWRzJTIyJTNBJTVCJTIyYmxvY2tfM2dwU0dta2dMNG5XU0JRaldDaksyeiUyMiUyQyUyMmJsb2NrX0JqcFE3REdUdHZhRXVZUk1kN1ZFN3clMjIlMkMlMjJibG9ja194eWc0R1dtZ0diSkpFRFJRYzc2YkMlMjIlMkMlMjJibG9ja183NlZwdExDWjQ3dDNFa0FhclV1ZkVKJTIyJTJDJTIyYmxvY2stMTcxNzE4NzQ4ODE1OCUyMiUyQyUyMmJsb2NrX0d0azNrRFl3c0pxRW1RZjJYR1dQUmMlMjIlMkMlMjJibG9ja19MQUNEQ3pVUzJic3ZFYm1ucTFLSHVXJTIyJTVEJTdEJTdEJTJDJTIyYmxvY2tfM2dwU0dta2dMNG5XU0JRaldDaksyeiUyMiUzQSU3QiUyMnR5cGUlMjIlM0ElMjJJbWFnZSUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJzdHlsZSUyMiUzQSU3QiUyMnBhZGRpbmclMjIlM0ElN0IlMjJ0b3AlMjIlM0EyNCUyQyUyMmJvdHRvbSUyMiUzQTglMkMlMjJyaWdodCUyMiUzQTI0JTJDJTIybGVmdCUyMiUzQTI0JTdEJTJDJTIyYmFja2dyb3VuZENvbG9yJTIyJTNBbnVsbCUyQyUyMnRleHRBbGlnbiUyMiUzQSUyMmxlZnQlMjIlN0QlMkMlMjJwcm9wcyUyMiUzQSU3QiUyMmhlaWdodCUyMiUzQTI0JTJDJTIydXJsJTIyJTNBJTIyaHR0cHMlM0ElMkYlMkZkMWlpdTU4OWczOW82Yy5jbG91ZGZyb250Lm5ldCUyRmxpdmUlMkZwbGF0Zm9ybXMlMkZwbGF0Zm9ybV9BOXd3S1NMNkVWNm9yaDZmJTJGaW1hZ2VzJTJGd3B0ZW1wbGF0ZWltYWdlX1hoMVIyM1U5eml5Y3Q5bmQlMkZjb2RvYy5wbmclMjIlMkMlMjJhbHQlMjIlM0ElMjIlMjIlMkMlMjJsaW5rSHJlZiUyMiUzQW51bGwlMkMlMjJjb250ZW50QWxpZ25tZW50JTIyJTNBJTIybWlkZGxlJTIyJTdEJTdEJTdEJTJDJTIyYmxvY2tfQmpwUTdER1R0dmFFdVlSTWQ3VkU3dyUyMiUzQSU3QiUyMnR5cGUlMjIlM0ElMjJIZWFkaW5nJTIyJTJDJTIyZGF0YSUyMiUzQSU3QiUyMnN0eWxlJTIyJTNBJTdCJTIyY29sb3IlMjIlM0FudWxsJTJDJTIyYmFja2dyb3VuZENvbG9yJTIyJTNBbnVsbCUyQyUyMmZvbnRGYW1pbHklMjIlM0FudWxsJTJDJTIyZm9udFdlaWdodCUyMiUzQSUyMmJvbGQlMjIlMkMlMjJ0ZXh0QWxpZ24lMjIlM0ElMjJsZWZ0JTIyJTJDJTIycGFkZGluZyUyMiUzQSU3QiUyMnRvcCUyMiUzQTMyJTJDJTIyYm90dG9tJTIyJTNBMCUyQyUyMmxlZnQlMjIlM0EyNCUyQyUyMnJpZ2h0JTIyJTNBMjQlN0QlN0QlMkMlMjJwcm9wcyUyMiUzQSU3QiUyMmxldmVsJTIyJTNBJTIyaDMlMjIlMkMlMjJ0ZXh0JTIyJTNBJTIyUmVzZXQlMjB5b3VyJTIwcGFzc3dvcmQlM0YlMjIlN0QlN0QlN0QlMkMlMjJibG9ja194eWc0R1dtZ0diSkpFRFJRYzc2YkMlMjIlM0ElN0IlMjJ0eXBlJTIyJTNBJTIyVGV4dCUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJzdHlsZSUyMiUzQSU3QiUyMmNvbG9yJTIyJTNBJTIyJTIzNDc0ODQ5JTIyJTJDJTIyYmFja2dyb3VuZENvbG9yJTIyJTNBbnVsbCUyQyUyMmZvbnRTaXplJTIyJTNBMTQlMkMlMjJmb250RmFtaWx5JTIyJTNBbnVsbCUyQyUyMmZvbnRXZWlnaHQlMjIlM0ElMjJub3JtYWwlMjIlMkMlMjJ0ZXh0QWxpZ24lMjIlM0ElMjJsZWZ0JTIyJTJDJTIycGFkZGluZyUyMiUzQSU3QiUyMnRvcCUyMiUzQTglMkMlMjJib3R0b20lMjIlM0ExNiUyQyUyMmxlZnQlMjIlM0EyNCUyQyUyMnJpZ2h0JTIyJTNBMjQlN0QlN0QlMkMlMjJwcm9wcyUyMiUzQSU3QiUyMnRleHQlMjIlM0ElMjJJZiUyMHlvdSUyMGRpZG4ndCUyMHJlcXVlc3QlMjBhJTIwcmVzZXQlMkMlMjBkb24ndCUyMHdvcnJ5LiUyMFlvdSUyMGNhbiUyMHNhZmVseSUyMGlnbm9yZSUyMHRoaXMlMjBlbWFpbC4lMjIlN0QlN0QlN0QlMkMlMjJibG9ja183NlZwdExDWjQ3dDNFa0FhclV1ZkVKJTIyJTNBJTdCJTIydHlwZSUyMiUzQSUyMkJ1dHRvbiUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJzdHlsZSUyMiUzQSU3QiUyMmJhY2tncm91bmRDb2xvciUyMiUzQW51bGwlMkMlMjJmb250U2l6ZSUyMiUzQTE0JTJDJTIyZm9udEZhbWlseSUyMiUzQW51bGwlMkMlMjJmb250V2VpZ2h0JTIyJTNBJTIyYm9sZCUyMiUyQyUyMnRleHRBbGlnbiUyMiUzQSUyMmxlZnQlMjIlMkMlMjJwYWRkaW5nJTIyJTNBJTdCJTIydG9wJTIyJTNBMTIlMkMlMjJib3R0b20lMjIlM0EzMiUyQyUyMnJpZ2h0JTIyJTNBMjQlMkMlMjJsZWZ0JTIyJTNBMjQlN0QlN0QlMkMlMjJwcm9wcyUyMiUzQSU3QiUyMmJ1dHRvbkJhY2tncm91bmRDb2xvciUyMiUzQSUyMiUyMzAwNjhGRiUyMiUyQyUyMmJ1dHRvblN0eWxlJTIyJTNBJTIycmVjdGFuZ2xlJTIyJTJDJTIyYnV0dG9uVGV4dENvbG9yJTIyJTNBJTIyJTIzRkZGRkZGJTIyJTJDJTIyZnVsbFdpZHRoJTIyJTNBZmFsc2UlMkMlMjJzaXplJTIyJTNBJTIybWVkaXVtJTIyJTJDJTIydGV4dCUyMiUzQSUyMkNoYW5nZSUyMG15JTIwcGFzc3dvcmQlMjIlMkMlMjJ1cmwlMjIlM0ElMjJodHRwcyUzQSUyRiUyRmV4YW1wbGUudXNld2F5cG9pbnQuY29tJTJGcmVzZXRfcGFzc3dvcmQlM0Z0b2tlbiUzRDAyOTM4NDA5ODA5dzhyMDlhODN3cjA5OGF3MCUyMiU3RCU3RCU3RCUyQyUyMmJsb2NrX0d0azNrRFl3c0pxRW1RZjJYR1dQUmMlMjIlM0ElN0IlMjJ0eXBlJTIyJTNBJTIyRGl2aWRlciUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJzdHlsZSUyMiUzQSU3QiUyMmJhY2tncm91bmRDb2xvciUyMiUzQW51bGwlMkMlMjJwYWRkaW5nJTIyJTNBJTdCJTIydG9wJTIyJTNBMTYlMkMlMjJib3R0b20lMjIlM0ExNiUyQyUyMmxlZnQlMjIlM0EyNCUyQyUyMnJpZ2h0JTIyJTNBMjQlN0QlN0QlMkMlMjJwcm9wcyUyMiUzQSU3QiUyMmxpbmVIZWlnaHQlMjIlM0ExJTJDJTIybGluZUNvbG9yJTIyJTNBJTIyJTIzRUVFRUVFJTIyJTdEJTdEJTdEJTJDJTIyYmxvY2tfTEFDREN6VVMyYnN2RWJtbnExS0h1VyUyMiUzQSU3QiUyMnR5cGUlMjIlM0ElMjJUZXh0JTIyJTJDJTIyZGF0YSUyMiUzQSU3QiUyMnN0eWxlJTIyJTNBJTdCJTIyY29sb3IlMjIlM0ElMjIlMjM0NzQ4NDklMjIlMkMlMjJiYWNrZ3JvdW5kQ29sb3IlMjIlM0FudWxsJTJDJTIyZm9udFNpemUlMjIlM0ExMiUyQyUyMmZvbnRGYW1pbHklMjIlM0FudWxsJTJDJTIyZm9udFdlaWdodCUyMiUzQSUyMm5vcm1hbCUyMiUyQyUyMnRleHRBbGlnbiUyMiUzQSUyMmxlZnQlMjIlMkMlMjJwYWRkaW5nJTIyJTNBJTdCJTIydG9wJTIyJTNBNCUyQyUyMmJvdHRvbSUyMiUzQTI0JTJDJTIybGVmdCUyMiUzQTI0JTJDJTIycmlnaHQlMjIlM0EyNCU3RCU3RCUyQyUyMnByb3BzJTIyJTNBJTdCJTIydGV4dCUyMiUzQSUyMk5lZWQlMjBoZWxwJTNGJTIwSnVzdCUyMHJlcGx5JTIwdG8lMjB0aGlzJTIwZW1haWwlMjB0byUyMGNvbnRhY3QlMjBzdXBwb3J0LiUyMiU3RCU3RCU3RCUyQyUyMmJsb2NrLTE3MTcxODc0ODgxNTglMjIlM0ElN0IlMjJ0eXBlJTIyJTNBJTIyQ29udGFpbmVyJTIyJTJDJTIyZGF0YSUyMiUzQSU3QiUyMnN0eWxlJTIyJTNBJTdCJTIycGFkZGluZyUyMiUzQSU3QiUyMnRvcCUyMiUzQTE2JTJDJTIyYm90dG9tJTIyJTNBMTYlMkMlMjJsZWZ0JTIyJTNBMjQlMkMlMjJyaWdodCUyMiUzQTI0JTdEJTdEJTJDJTIycHJvcHMlMjIlM0ElN0IlMjJjaGlsZHJlbklkcyUyMiUzQSU1QiUyMmJsb2NrLTE3MTcxODc0OTI5MTYlMjIlNUQlN0QlN0QlN0QlMkMlMjJibG9jay0xNzE3MTg3NDkyOTE2JTIyJTNBJTdCJTIydHlwZSUyMiUzQSUyMkNvbnRhaW5lciUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJzdHlsZSUyMiUzQSU3QiUyMmJhY2tncm91bmRDb2xvciUyMiUzQSUyMiUyM2U5ZWRmNSUyMiUyQyUyMmJvcmRlclJhZGl1cyUyMiUzQTglMkMlMjJwYWRkaW5nJTIyJTNBJTdCJTIydG9wJTIyJTNBMTYlMkMlMjJib3R0b20lMjIlM0ExNiUyQyUyMnJpZ2h0JTIyJTNBMjQlMkMlMjJsZWZ0JTIyJTNBMjQlN0QlN0QlMkMlMjJwcm9wcyUyMiUzQSU3QiUyMmNoaWxkcmVuSWRzJTIyJTNBJTVCJTIyYmxvY2stMTcxNzE4NzUwNjc2OSUyMiU1RCU3RCU3RCU3RCUyQyUyMmJsb2NrLTE3MTcxODc1MDY3NjklMjIlM0ElN0IlMjJ0eXBlJTIyJTNBJTIyVGV4dCUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJzdHlsZSUyMiUzQSU3QiUyMmNvbG9yJTIyJTNBJTIyJTIzNzE3MTcxJTIyJTJDJTIyZm9udFNpemUlMjIlM0ExMiUyQyUyMmZvbnRXZWlnaHQlMjIlM0ElMjJub3JtYWwlMjIlMkMlMjJ0ZXh0QWxpZ24lMjIlM0ElMjJsZWZ0JTIyJTJDJTIycGFkZGluZyUyMiUzQSU3QiUyMnRvcCUyMiUzQTAlMkMlMjJib3R0b20lMjIlM0EwJTJDJTIycmlnaHQlMjIlM0EwJTJDJTIybGVmdCUyMiUzQTAlN0QlN0QlMkMlMjJwcm9wcyUyMiUzQSU3QiUyMm1hcmtkb3duJTIyJTNBdHJ1ZSUyQyUyMnRleHQlMjIlM0ElMjJBY2Nlc3MlMjBkZXRhaWxzJTNBJTVDbiU1Q24tJTIwQWNjb3VudCUzQSUyMGpvcmRhbmlzaXAlNUNuLSUyMFdoZW4lM0ElMjAyMDI0LTA1LTI4JTIwMDElM0ExNCUzQTA3JTIwVVQlNUNuLSUyMERldmljZSUzQSUyME1vemlsbGElMkY1LjAlNUNuJTVDbiU1QlZpZXclMjBmdWxsJTIwbG9nJTIwcmVwb3J0JTVEKGh0dHBzJTNBJTJGJTJGdXNld2F5cG9pbnQuY29tKSUyMiU3RCU3RCU3RCU3RA==).

Hope that helps!

**Comment by arunudayan** [comment]
There is one problem with this approach though. If someone has stored predefined links and wants to select one from a dropdown list and set it as a hyperlink. It wont be a lot intuitive. I guess the email writers need to know markdown.
