### ISSUE TITLE
integrate in php

### ISSUE THREAD

**Issue by RAEMO2** [usewaypoint/email-builder-js#104]
I am new to js. Can I have a steps to integrate email-builder in my php project.

Facing below issue
![image](https://github.com/usewaypoint/email-builder-js/assets/92026196/9a987b94-3031-4d77-b009-0bce3ee08615)

**Comment by jordanisip** [comment]
Unfortunately, we don't have any experience with php so we are unable to help here. If you end up using Node, you can look at our self-hosting instructions here: https://github.com/usewaypoint/email-builder-js?tab=readme-ov-file#self-hosting-the-editor

**Comment by RAEMO2** [comment]
Okay thank you. But, I need some developer documentation. i.e., hiding left navigation bar(template area). Hiding some top options (like, download JSON file, Import JSON). Where can I find this details. I could not see any documents in the github. Could you please share the details
