### ISSUE TITLE
Is there a way to use this in vue/nuxt?

### ISSUE THREAD

**Issue by Q16solver** [usewaypoint/email-builder-js#105]
Hi! I saw this package in reddit and was very interested in its capabilities and wanted to see if I can hook it up to my nuxt application!

I know it's built with react, but there's been some working going on with web components or the [veaury](https://github.com/gloriasoft/veaury) package, so maybe there is a way I can convert it to web component and use it in vue, just want to get a confirmation on if this is feasible before I try, thanks

**Comment by Q16solver** [comment]
Also a bit of a separate issue, I noticed that EmailLayout is also used to build the block configuration, coudl that also be exported out as a package for convenience? that would be great!

**Comment by jordanisip** [comment]
Unfortunately, we don't have any experience with Vue, so we won't be able to help here. You are more than welcome to create a Vue fork if you are up for it as I'm sure there are others in the same boat.

Putting the root EmailLayout data in a separate block configuration with it's own package is an interesting idea. We're going to punt on this for now but we'll keep it in mind and consider it further if others find the need for it in the future.
