### ISSUE TITLE
Developer Documentation

### ISSUE THREAD

**Issue by RAEMO2** [usewaypoint/email-builder-js#108]
I need some developer documentation. i.e., After integration with my project, hiding left navigation bar(template area), hiding some top options (like, download JSON file, Import JSON), read the editor content from Javascript. Where can I find this details. I could not see any documents in the github. Could you please share the details

**Comment by jordanisip** [comment]
This level of customization and documentation is outside the scope for this project.

However, if you are self-hosting, I'd recommend looking [this file](https://github.com/usewaypoint/email-builder-js/blob/main/packages/editor-sample/src/App/TemplatePanel/index.tsx) in the `editor-sample` package (which is what is shown on the [playground](https://usewaypoint.github.io/email-builder-js/#sample/reservation-reminder)).
