### ISSUE TITLE
What is the LICENSE

### ISSUE THREAD

**Issue by niklauslee** [usewaypoint/email-builder-js#113]
Thank you for the awesome project. However, there is no clear license. Under what license is it distributed? MIT, Apache, MPL, GPL or else...?

**Comment by jordanisip** [comment]
Hi @niklauslee, we previously had the licenses on each of the packages (MIT). However, we've now bumped up the license ([PR](https://github.com/usewaypoint/email-builder-js/pull/114/files)) at the project/repo level as well. 

Going to the [project page](https://github.com/usewaypoint/email-builder-js), you should now see the MIT license setup on it.
