### ISSUE TITLE
I need to display the email editor in browser like in UI Screen, which am using angular and HTML

### ISSUE THREAD

**Issue by Kikovenu** [usewaypoint/email-builder-js#123]
I'm trying to build an email editor using pure Angular and HTML. I need to be able to read the content from the editor, insert custom HTML elements, and display the result on the screen. I've managed to configure the editor to render, but it's not appearing in the UI. Can you help me troubleshoot this issue?

**Comment by cohitre** [comment]
The project is written in React and meant to be used with React applications. We cannot help troubleshoot an angular issue.

**Comment by Kikovenu** [comment]
Thank you
