### ISSUE TITLE
Border radius not correctly applied

### ISSUE THREAD

**Issue by nicktc** [usewaypoint/email-builder-js#79]
Hey,

Loving what you guys are doing with this email builder. I noticed a small bug. When applying a border radius to a container, the border radius is not correctly applied. Nothing happens with the borders, unless you specify a border color. In that case, only the border itself will be rounded, instead of the container itself. Notice the white background color in the corners:

![Scherm­afbeelding 2024-04-12 om 10 28 06](https://github.com/usewaypoint/email-builder-js/assets/2048475/c261aa35-89bb-472c-882b-1a6b7ecefdad)

Used the following settings:

![Scherm­afbeelding 2024-04-12 om 10 28 10](https://github.com/usewaypoint/email-builder-js/assets/2048475/c40df2da-2385-4412-8737-ad4d9ec983d1)

When I apply a border radius, I expect this to work, also when no specific border color is specified. Next to that you can only define the border radius for the full container, you can choose to have a different radius for the left top corner and the right top corner only. Having this ability will allow users to create also beautiful rounded templates. Now the builder only supports rectangular designs.

**Comment by jordanisip** [comment]
Hi @nicktc, appreciate the kind words and thanks for this ticket submission. Looks like this is indeed a bug and we're seeing it on our end as well. While it appears the border radius is being applied to the div, the table behind it seems to be using it's own background color. 

We'll take a look and get this fixed.

**Comment by jordanisip** [comment]
Hi @nicktc, good news – we were able to put in a fix for this. You can see the rounded corners in action on [this template in the playground](https://usewaypoint.github.io/email-builder-js/#code/JTdCJTIycm9vdCUyMiUzQSU3QiUyMnR5cGUlMjIlM0ElMjJFbWFpbExheW91dCUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJiYWNrZHJvcENvbG9yJTIyJTNBJTIyJTIzRjJGNUY3JTIyJTJDJTIyYm9yZGVyUmFkaXVzJTIyJTNBMjQlMkMlMjJjYW52YXNDb2xvciUyMiUzQSUyMiUyM0ZGRkZGRiUyMiUyQyUyMnRleHRDb2xvciUyMiUzQSUyMiUyMzI0MjQyNCUyMiUyQyUyMmZvbnRGYW1pbHklMjIlM0ElMjJNT0RFUk5fU0FOUyUyMiUyQyUyMmNoaWxkcmVuSWRzJTIyJTNBJTVCJTIyYmxvY2tfM2dwU0dta2dMNG5XU0JRaldDaksyeiUyMiUyQyUyMmJsb2NrX0JqcFE3REdUdHZhRXVZUk1kN1ZFN3clMjIlMkMlMjJibG9ja194eWc0R1dtZ0diSkpFRFJRYzc2YkMlMjIlMkMlMjJibG9ja183NlZwdExDWjQ3dDNFa0FhclV1ZkVKJTIyJTJDJTIyYmxvY2stMTcxNzE4NzQ4ODE1OCUyMiUyQyUyMmJsb2NrX0d0azNrRFl3c0pxRW1RZjJYR1dQUmMlMjIlMkMlMjJibG9ja19MQUNEQ3pVUzJic3ZFYm1ucTFLSHVXJTIyJTVEJTdEJTdEJTJDJTIyYmxvY2tfM2dwU0dta2dMNG5XU0JRaldDaksyeiUyMiUzQSU3QiUyMnR5cGUlMjIlM0ElMjJJbWFnZSUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJzdHlsZSUyMiUzQSU3QiUyMnBhZGRpbmclMjIlM0ElN0IlMjJ0b3AlMjIlM0EyNCUyQyUyMmJvdHRvbSUyMiUzQTglMkMlMjJyaWdodCUyMiUzQTI0JTJDJTIybGVmdCUyMiUzQTI0JTdEJTJDJTIyYmFja2dyb3VuZENvbG9yJTIyJTNBbnVsbCUyQyUyMnRleHRBbGlnbiUyMiUzQSUyMmxlZnQlMjIlN0QlMkMlMjJwcm9wcyUyMiUzQSU3QiUyMmhlaWdodCUyMiUzQTI0JTJDJTIydXJsJTIyJTNBJTIyaHR0cHMlM0ElMkYlMkZkMWlpdTU4OWczOW82Yy5jbG91ZGZyb250Lm5ldCUyRmxpdmUlMkZwbGF0Zm9ybXMlMkZwbGF0Zm9ybV9BOXd3S1NMNkVWNm9yaDZmJTJGaW1hZ2VzJTJGd3B0ZW1wbGF0ZWltYWdlX1hoMVIyM1U5eml5Y3Q5bmQlMkZjb2RvYy5wbmclMjIlMkMlMjJhbHQlMjIlM0ElMjIlMjIlMkMlMjJsaW5rSHJlZiUyMiUzQW51bGwlMkMlMjJjb250ZW50QWxpZ25tZW50JTIyJTNBJTIybWlkZGxlJTIyJTdEJTdEJTdEJTJDJTIyYmxvY2tfQmpwUTdER1R0dmFFdVlSTWQ3VkU3dyUyMiUzQSU3QiUyMnR5cGUlMjIlM0ElMjJIZWFkaW5nJTIyJTJDJTIyZGF0YSUyMiUzQSU3QiUyMnN0eWxlJTIyJTNBJTdCJTIyY29sb3IlMjIlM0FudWxsJTJDJTIyYmFja2dyb3VuZENvbG9yJTIyJTNBbnVsbCUyQyUyMmZvbnRGYW1pbHklMjIlM0FudWxsJTJDJTIyZm9udFdlaWdodCUyMiUzQSUyMmJvbGQlMjIlMkMlMjJ0ZXh0QWxpZ24lMjIlM0ElMjJsZWZ0JTIyJTJDJTIycGFkZGluZyUyMiUzQSU3QiUyMnRvcCUyMiUzQTMyJTJDJTIyYm90dG9tJTIyJTNBMCUyQyUyMmxlZnQlMjIlM0EyNCUyQyUyMnJpZ2h0JTIyJTNBMjQlN0QlN0QlMkMlMjJwcm9wcyUyMiUzQSU3QiUyMmxldmVsJTIyJTNBJTIyaDMlMjIlMkMlMjJ0ZXh0JTIyJTNBJTIyUmVzZXQlMjB5b3VyJTIwcGFzc3dvcmQlM0YlMjIlN0QlN0QlN0QlMkMlMjJibG9ja194eWc0R1dtZ0diSkpFRFJRYzc2YkMlMjIlM0ElN0IlMjJ0eXBlJTIyJTNBJTIyVGV4dCUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJzdHlsZSUyMiUzQSU3QiUyMmNvbG9yJTIyJTNBJTIyJTIzNDc0ODQ5JTIyJTJDJTIyYmFja2dyb3VuZENvbG9yJTIyJTNBbnVsbCUyQyUyMmZvbnRTaXplJTIyJTNBMTQlMkMlMjJmb250RmFtaWx5JTIyJTNBbnVsbCUyQyUyMmZvbnRXZWlnaHQlMjIlM0ElMjJub3JtYWwlMjIlMkMlMjJ0ZXh0QWxpZ24lMjIlM0ElMjJsZWZ0JTIyJTJDJTIycGFkZGluZyUyMiUzQSU3QiUyMnRvcCUyMiUzQTglMkMlMjJib3R0b20lMjIlM0ExNiUyQyUyMmxlZnQlMjIlM0EyNCUyQyUyMnJpZ2h0JTIyJTNBMjQlN0QlN0QlMkMlMjJwcm9wcyUyMiUzQSU3QiUyMnRleHQlMjIlM0ElMjJJZiUyMHlvdSUyMGRpZG4ndCUyMHJlcXVlc3QlMjBhJTIwcmVzZXQlMkMlMjBkb24ndCUyMHdvcnJ5LiUyMFlvdSUyMGNhbiUyMHNhZmVseSUyMGlnbm9yZSUyMHRoaXMlMjBlbWFpbC4lMjIlN0QlN0QlN0QlMkMlMjJibG9ja183NlZwdExDWjQ3dDNFa0FhclV1ZkVKJTIyJTNBJTdCJTIydHlwZSUyMiUzQSUyMkJ1dHRvbiUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJzdHlsZSUyMiUzQSU3QiUyMmJhY2tncm91bmRDb2xvciUyMiUzQW51bGwlMkMlMjJmb250U2l6ZSUyMiUzQTE0JTJDJTIyZm9udEZhbWlseSUyMiUzQW51bGwlMkMlMjJmb250V2VpZ2h0JTIyJTNBJTIyYm9sZCUyMiUyQyUyMnRleHRBbGlnbiUyMiUzQSUyMmxlZnQlMjIlMkMlMjJwYWRkaW5nJTIyJTNBJTdCJTIydG9wJTIyJTNBMTIlMkMlMjJib3R0b20lMjIlM0EzMiUyQyUyMnJpZ2h0JTIyJTNBMjQlMkMlMjJsZWZ0JTIyJTNBMjQlN0QlN0QlMkMlMjJwcm9wcyUyMiUzQSU3QiUyMmJ1dHRvbkJhY2tncm91bmRDb2xvciUyMiUzQSUyMiUyMzAwNjhGRiUyMiUyQyUyMmJ1dHRvblN0eWxlJTIyJTNBJTIycmVjdGFuZ2xlJTIyJTJDJTIyYnV0dG9uVGV4dENvbG9yJTIyJTNBJTIyJTIzRkZGRkZGJTIyJTJDJTIyZnVsbFdpZHRoJTIyJTNBZmFsc2UlMkMlMjJzaXplJTIyJTNBJTIybWVkaXVtJTIyJTJDJTIydGV4dCUyMiUzQSUyMkNoYW5nZSUyMG15JTIwcGFzc3dvcmQlMjIlMkMlMjJ1cmwlMjIlM0ElMjJodHRwcyUzQSUyRiUyRmV4YW1wbGUudXNld2F5cG9pbnQuY29tJTJGcmVzZXRfcGFzc3dvcmQlM0Z0b2tlbiUzRDAyOTM4NDA5ODA5dzhyMDlhODN3cjA5OGF3MCUyMiU3RCU3RCU3RCUyQyUyMmJsb2NrX0d0azNrRFl3c0pxRW1RZjJYR1dQUmMlMjIlM0ElN0IlMjJ0eXBlJTIyJTNBJTIyRGl2aWRlciUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJzdHlsZSUyMiUzQSU3QiUyMmJhY2tncm91bmRDb2xvciUyMiUzQW51bGwlMkMlMjJwYWRkaW5nJTIyJTNBJTdCJTIydG9wJTIyJTNBMTYlMkMlMjJib3R0b20lMjIlM0ExNiUyQyUyMmxlZnQlMjIlM0EyNCUyQyUyMnJpZ2h0JTIyJTNBMjQlN0QlN0QlMkMlMjJwcm9wcyUyMiUzQSU3QiUyMmxpbmVIZWlnaHQlMjIlM0ExJTJDJTIybGluZUNvbG9yJTIyJTNBJTIyJTIzRUVFRUVFJTIyJTdEJTdEJTdEJTJDJTIyYmxvY2tfTEFDREN6VVMyYnN2RWJtbnExS0h1VyUyMiUzQSU3QiUyMnR5cGUlMjIlM0ElMjJUZXh0JTIyJTJDJTIyZGF0YSUyMiUzQSU3QiUyMnN0eWxlJTIyJTNBJTdCJTIyY29sb3IlMjIlM0ElMjIlMjM0NzQ4NDklMjIlMkMlMjJiYWNrZ3JvdW5kQ29sb3IlMjIlM0FudWxsJTJDJTIyZm9udFNpemUlMjIlM0ExMiUyQyUyMmZvbnRGYW1pbHklMjIlM0FudWxsJTJDJTIyZm9udFdlaWdodCUyMiUzQSUyMm5vcm1hbCUyMiUyQyUyMnRleHRBbGlnbiUyMiUzQSUyMmxlZnQlMjIlMkMlMjJwYWRkaW5nJTIyJTNBJTdCJTIydG9wJTIyJTNBNCUyQyUyMmJvdHRvbSUyMiUzQTI0JTJDJTIybGVmdCUyMiUzQTI0JTJDJTIycmlnaHQlMjIlM0EyNCU3RCU3RCUyQyUyMnByb3BzJTIyJTNBJTdCJTIydGV4dCUyMiUzQSUyMk5lZWQlMjBoZWxwJTNGJTIwSnVzdCUyMHJlcGx5JTIwdG8lMjB0aGlzJTIwZW1haWwlMjB0byUyMGNvbnRhY3QlMjBzdXBwb3J0LiUyMiU3RCU3RCU3RCUyQyUyMmJsb2NrLTE3MTcxODc0ODgxNTglMjIlM0ElN0IlMjJ0eXBlJTIyJTNBJTIyQ29udGFpbmVyJTIyJTJDJTIyZGF0YSUyMiUzQSU3QiUyMnN0eWxlJTIyJTNBJTdCJTIycGFkZGluZyUyMiUzQSU3QiUyMnRvcCUyMiUzQTE2JTJDJTIyYm90dG9tJTIyJTNBMTYlMkMlMjJsZWZ0JTIyJTNBMjQlMkMlMjJyaWdodCUyMiUzQTI0JTdEJTdEJTJDJTIycHJvcHMlMjIlM0ElN0IlMjJjaGlsZHJlbklkcyUyMiUzQSU1QiUyMmJsb2NrLTE3MTcxODc0OTI5MTYlMjIlNUQlN0QlN0QlN0QlMkMlMjJibG9jay0xNzE3MTg3NDkyOTE2JTIyJTNBJTdCJTIydHlwZSUyMiUzQSUyMkNvbnRhaW5lciUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJzdHlsZSUyMiUzQSU3QiUyMmJhY2tncm91bmRDb2xvciUyMiUzQSUyMiUyM2U5ZWRmNSUyMiUyQyUyMmJvcmRlclJhZGl1cyUyMiUzQTglMkMlMjJwYWRkaW5nJTIyJTNBJTdCJTIydG9wJTIyJTNBMTYlMkMlMjJib3R0b20lMjIlM0ExNiUyQyUyMnJpZ2h0JTIyJTNBMjQlMkMlMjJsZWZ0JTIyJTNBMjQlN0QlN0QlMkMlMjJwcm9wcyUyMiUzQSU3QiUyMmNoaWxkcmVuSWRzJTIyJTNBJTVCJTIyYmxvY2stMTcxNzE4NzUwNjc2OSUyMiU1RCU3RCU3RCU3RCUyQyUyMmJsb2NrLTE3MTcxODc1MDY3NjklMjIlM0ElN0IlMjJ0eXBlJTIyJTNBJTIyVGV4dCUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJzdHlsZSUyMiUzQSU3QiUyMmNvbG9yJTIyJTNBJTIyJTIzNzE3MTcxJTIyJTJDJTIyZm9udFNpemUlMjIlM0ExMiUyQyUyMmZvbnRXZWlnaHQlMjIlM0ElMjJub3JtYWwlMjIlMkMlMjJ0ZXh0QWxpZ24lMjIlM0ElMjJsZWZ0JTIyJTJDJTIycGFkZGluZyUyMiUzQSU3QiUyMnRvcCUyMiUzQTAlMkMlMjJib3R0b20lMjIlM0EwJTJDJTIycmlnaHQlMjIlM0EwJTJDJTIybGVmdCUyMiUzQTAlN0QlN0QlMkMlMjJwcm9wcyUyMiUzQSU3QiUyMm1hcmtkb3duJTIyJTNBdHJ1ZSUyQyUyMnRleHQlMjIlM0ElMjItJTIwQWNjb3VudCUzQSUyMGpvcmRhbmlzaXAlNUNuLSUyMFdoZW4lM0ElMjAyMDI0LTA1LTI4JTIwMDElM0ExNCUzQTA3JTIwVVQlNUNuLSUyMERldmljZSUzQSUyME1vemlsbGElMkY1LjAlMjIlN0QlN0QlN0QlN0Q=).

![CleanShot 2024-05-31 at 16 33 39](https://github.com/usewaypoint/email-builder-js/assets/5899/24f0718d-1fa1-49a9-b180-433836980a6a)

Let me know if that solves the issue on your end :)

**Comment by nicktc** [comment]
Nice!
