### ISSUE TITLE
Allow to export and import the JSON

### ISSUE THREAD

**Issue by nicktc** [usewaypoint/email-builder-js#81]
In the builder it would be cool if you can export the JSON, or import it. So that I can store an email design locally, and when I like to tweak it import (or copy paste) the JSON again, so that I can continu designing the email template.

**Comment by jordanisip** [comment]
Great thinking. This is on our list to add!

**Comment by nicktc** [comment]
Great! 🤩

**Comment by jordanisip** [comment]
Hi @nicktc, great news – we (mainly @cohitre) were able to add a way to easily download and import a JSON from the builder. 

![CleanShot 2024-04-15 at 11 01 04](https://github.com/usewaypoint/email-builder-js/assets/5899/7ccfcea5-f2c6-4429-8600-cbd1eab9835e)

You can see it live on our [playground](https://usewaypoint.github.io/email-builder-js/#sample/reset-password). 

We hope to be able to import by file in the future but a copy and paste seemed like a good quick feature in the meantime :)
