### ISSUE TITLE
New lines aren't being applied

### ISSUE THREAD

**Issue by nicktc** [usewaypoint/email-builder-js#84]
When using a text block it would be helpful if it supports new lines. Whenever I add a new line in the text, it's not applied in the design. Not sure if this is a conscious decision? Because of the not supporting of new lines, most blocks have to be converted to a HTML block, which feels overkill.

<img width="698" alt="Scherm­afbeelding 2024-04-14 om 09 58 05" src="https://github.com/usewaypoint/email-builder-js/assets/2048475/3154c080-8c39-46b2-881c-63a5510d5b2c">
<img width="337" alt="Scherm­afbeelding 2024-04-14 om 09 58 09" src="https://github.com/usewaypoint/email-builder-js/assets/2048475/f261d20d-e1cc-4315-9831-205a85e52bfc">

**Comment by jordanisip** [comment]
At the moment, we made the decision to use plain text for the text blocks. We may consider adding Markdown (like on our Pro builder) in the future – either as a separate block or as part of the text block.

**Comment by jordanisip** [comment]
Good news, we've added a 'Markdown' option on Text blocks to solve this. When turned on, it will process the text through a [Markdown](https://www.markdownguide.org/cheat-sheet/) processor which will respect the line breaks and allow for basic formatting syntax.

![CleanShot 2024-05-31 at 16 45 41](https://github.com/usewaypoint/email-builder-js/assets/5899/953d41d6-8be9-46cb-84be-069e7e871e31)

Hope that helps!

**Comment by nicktc** [comment]
Cool!
