### ISSUE TITLE
Compile lib as CommonJS

### ISSUE THREAD

**Issue by ljacho** [usewaypoint/email-builder-js#95]
Including email-builder-js is strictly limited as it is not CommonJS compiled. 

Here is CommonJS compiled version: [lib](https://github.com/ljacho/email-builder-test/tree/master/src/usewaypoint)

Here is TS working example, lib added to srouce: [sample](https://github.com/ljacho/email-builder-test)

**Comment by erikmeliska** [comment]
works for me!

**Comment by cohitre** [comment]
This functionality is now in the main branch
