### ISSUE TITLE
Your brand name on the email builder

### ISSUE THREAD

**Issue by Kikovenu** [usewaypoint/email-builder-js#99]
Hey there,

I'm curious if your brand name is displayed on the email editor upon integration and usage. Additionally, could you confirm if it's compatible with Angular 17? 

Thanks

Kiko

-LOOKING FOR MORE?
Waypoint is an email API service with a hosted 'pro' template builder with Markdown, dynamic variables, loops, conditionals, drag and drop, layouts, and more.

**Comment by jordanisip** [comment]
Hi, it does not (on both, EmailBuilder.js and on Waypoint). 

Regarding EmailBuilder.js, the output you see on the [playground](https://usewaypoint.github.io/email-builder-js/#sample/reservation-reminder) is the exact output shown on the emails – and you can see and edit the HTML.

**Comment by Kikovenu** [comment]
Thanks Jordani
